INSERT INTO ARTICULO_CATEGORIA (CODIGO, DESCRIPCION) VALUES
  ('CALZADO', 'Calzado'),
  ('ROPA', 'Moda deportiva'),
  ('BANO', 'Articulos de baño / natación');

INSERT INTO ARTICULO_TIPO (CODIGO, ID_ARTICULO_CATEGORIA, DESCRIPCION) VALUES
  ('ZAPATILLA', (SELECT ID FROM ARTICULO_CATEGORIA WHERE CODIGO = 'CALZADO'), 'Zapatillas deportivas'),
  ('MALLA', (SELECT ID FROM ARTICULO_CATEGORIA WHERE CODIGO = 'ROPA'), 'Mallas deportivas'),
  ('CHAQUETA', (SELECT ID FROM ARTICULO_CATEGORIA WHERE CODIGO = 'ROPA'), 'Chaquetas deportivas'),
  ('BOTAS', (SELECT ID FROM ARTICULO_CATEGORIA WHERE CODIGO = 'CALZADO'), 'Botas de montaña'),
  ('BANADOR', (SELECT ID FROM ARTICULO_CATEGORIA WHERE CODIGO = 'BANO'), 'Bañador');

INSERT INTO ARTICULO (CODIGO, ID_ARTICULO_TIPO, DESCRIPCION, PRECIO_EUROS, ULTIMA_MODIFICACION) VALUES
  ('CONVERSE-BOULEVARD', (SELECT ID FROM ARTICULO_TIPO WHERE CODIGO = 'ZAPATILLA'), 'Zapatillas deportivas Converse Boulevard para hombre', 49.99, NULL),
  ('ASICS-ICON', (SELECT ID FROM ARTICULO_TIPO WHERE CODIGO = 'MALLA'), 'Mallas de running Ascis Icon para mujer', 54.99, NULL),
  ('THE-NORTH-FACE-QUEST', (SELECT ID FROM ARTICULO_TIPO WHERE CODIGO = 'CHAQUETA'), 'Chaqueta de hombre para deportes de montaña de la marca The North Face', 149.99, '2022-11-06 23.03.10'),
  ('ADIDAS-TERREX-AX3', (SELECT ID FROM ARTICULO_TIPO WHERE CODIGO = 'BOTAS'), 'Botas de montaña para hombre Adidas Terrex AX3', 159.99, NULL),
  ('PUMA-RACERBACK', (SELECT ID FROM ARTICULO_TIPO WHERE CODIGO = 'BANADOR'), 'Bañador de la marca Puma para mujer', 34.99, NULL),
  ('BOTAS-CHIRUCA-MONTREAL', (SELECT ID FROM ARTICULO_TIPO WHERE CODIGO = 'BOTAS'), 'Botas de montaña Chiruca para hombre', 119.99, '2022-10-21 11.24.11');