DROP TABLE IF EXISTS ARTICULO;

CREATE TABLE ARTICULO (
	ID BIGINT AUTO_INCREMENT PRIMARY KEY,
	CODIGO VARCHAR(40) NOT NULL,
	DESCRIPCION VARCHAR(500),
	PRECIO_EUROS NUMERIC(20,2),
	ULTIMA_MODIFICACION TIMESTAMP
);

ALTER TABLE ARTICULO ADD CONSTRAINT AK_ARTICULO UNIQUE (CODIGO);